services:
  - type: web
    name: intelligent-query-system
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY  
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-west1-gcp
      - key: PINECONE_INDEX_NAME
        value: document-embeddings
      - key: MONGODB_DATABASE
        value: intelligent_query_system
